---
- name: set ami and user based on Operating System
  set_fact:
    ami_reposerver: "{{ami_fedora22}}"
    rem_user_reposerer: fedora
  when: reposerver_os =="fedora22"
- name: set ami and user based on Operating System
  set_fact:
    ami_reposerver: "{{ami_rhel7}}"
    rem_user_reposerer: ec2-user
  when: reposerver_os =="rhel7"
- name: set ami and user based on Operating System
  set_fact:
    ami_reposerver: "{{ami_rhel6}}"
    rem_user_reposerer: ec2-user
  when: reposerver_os =="rhel6"
- name: set ami and user based on Operating System
  set_fact:
    ami_auto_runner: "{{ami_fedora22}}"
    rem_user_auto_runner: fedora
  when: auto_runner_os =="fedora22"
- name: set ami and user based on Operating System
  set_fact:
    ami_auto_runner: "{{ami_rhel7}}"
    rem_user_auto_runner: ec2-user
  when: auto_runner_os =="rhel7"
- name: set ami and user based on Operating System
  set_fact:
    ami_auto_runner: "{{ami_rhel6}}"
    rem_user_auto_runner: ec2-user
  when: auto_runner_os =="rhel6"
- name: set ami and user based on Operating System
  set_fact:
    automation_ami: "{{ami_fedora22}}"
    automation_rem_user: fedora
  when: automation_os =="fedora22"
- name: set ami and user based on Operating System
  set_fact:
    automation_ami: "{{ami_rhel7}}"
    automation_rem_user: ec2-user
  when: automation_os =="rhel7"
- name: set ami and user based on Operating System
  set_fact:
    automation_ami: "{{ami_rhel6}}"
    automation_rem_user: ec2-user
  when: automation_os =="rhel6"
