---
- include: test-cases/single-node/run.yml
- include: test-cases/single-stable-to-latest/run-stable.yml
- include: test-cases/single-stable-to-latest/run-latest.yml
- name: Create index file for publishing results
  hosts: localhost
  roles:
    - html-publish-find-all
    - html-publish-create-index
