---
- name: Setup repositories
  hosts:
    - "tag_Name_{{automation_name}}_automation_runner"
  roles:
    - set-package-manager
    - epel-repo-setup

- name: Prepare environment
  hosts:
    - "tag_Name_{{automation_name}}_automation_runner"
  tasks:
    - name: install necessarry packages
      action: "{{package_manager}} name={{ item }} state=present"
      with_items:
        - git
        - svn
        - python-pip
        - python-devel
        - m2crypto
        - python-crypto
        - gcc
        - dnf
        - libxslt-devel
    - pip: name=gevent state=present chdir={{automation_dir}}
    - pip: name=stitches state=present chdir={{automation_dir}}
    - pip: name=nose-html-reporting state=present
    - pip: name="http://svn.apache.org/repos/asf/qpid/trunk/qpid/python/" state=present
    - name: generate key for communicating with hosts
      command: "ssh-keygen -f /root/.ssh/test_rsa -N ''"

- name: Prepare environment
  hosts:
    - "tag_Name_{{automation_name}}_automation_runner"
  roles:
    - bashrc-config
