---
- name: Manage services pulp_resource_manager, pulp_workers & pulp_celerybeat
  service: name={{item}} state={{state}} enabled={{enabled}}
  with_items:
    - pulp_workers
    - pulp_resource_manager
    - pulp_celerybeat
