---
ROLES:
  pulp: &PULP
    auth: [admin, admin]
    url: "https://{{hostvars[groups['tag_Name_'+automation_name+'_'+tested_version|replace('.','_')+'_'+automation_os+'_'+producer_node][0]]['ec2_public_dns_name']}}/"
    hostname: "{{hostvars[groups['tag_Name_'+automation_name+'_'+tested_version|replace('.','_')+'_'+automation_os+'_'+producer_node][0]]['ec2_public_dns_name']}}"
    verify_api_ssl: 'myca.crt'
    version: "{{tested_version}}"
  qpid: &QPID
    url: "{{hostvars[groups['tag_Name_'+automation_name+'_'+tested_version|replace('.','_')+'_'+automation_os+'_'+producer_node][0]]['ec2_public_dns_name']}}"
  proxy: &SQUID
    host:
    port:
    username:
    password:
  repos:
    - &ZOO
      id: zoo
      type: rpm
      feed: "https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo/"
      display_name: ZOo rEPO
      proxy: 
      tags: ['default', 'small', 'demo']
  consumers:
  - &MY_CONSUMER
    id: my_consumer
    hostname: "{{hostvars[groups['tag_Name_'+automation_name+'_'+tested_version|replace('.','_')+'_'+automation_os+'_'+consumer_node][0]]['ec2_public_dns_name']}}"
    ssh_key: /root/.ssh/test_rsa
    verify: True
    ca_path: /etc/pki/tls/certs/myca.crt
    os:
      name: {{ansible_distribution}}
      version: {{ansible_distribution_version}}
    repos:
    - *ZOO
    pulp: *PULP
    tags: ['default']
  nodes:
    - &node_01
      auth:
      hostname:
      url:
      verify_api_ssl:
      display_name:
      description:
      pulp:
      QPID:
